options = -std=c11 -Wall -pedantic -g -fsanitize=undefined -fsanitize=address

hello: hello.c
	clang $(options) hello.c -o hello

fullpaint: fullpaint.c
	clang $(options) fullpaint.c -o fullpaint

square: square.c
	clang $(options) square.c -o square

interest: interest.c
	clang $(options) interest.c -o interest

maxint: maxint.c
	clang $(options) maxint.c -o maxint
